# Copyright 2025 Goldman Sachs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Publish Docker Image
description: Builds and pushes the image

inputs:
  docker_username:
    description: 'Docker Hub Username'
    required: true
  docker_password:
    description: 'Docker Hub Password'
    required: true
  image_tag:
    description: 'Image Tag'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build and Push Docker image
      shell: bash
      run: |
        docker build -t ${{ inputs.docker_username }}/pylegend-img:${{ inputs.image_tag }} .
        docker login -u ${{ inputs.docker_username }} -p ${{ inputs.docker_password }}
        docker push ${{ inputs.docker_username }}/pylegend-img:${{ inputs.image_tag }}
        
